language: c
jobs:
  include:
    - os: linux
      env: GENERATOR="Unix Makefiles"
      sudo: required
      before_script:
        - test -e /usr/bin/cmake || sudo ln -s $(which cmake) /usr/bin/cmake
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp
          DO_CMD=sudo bash
    - os: osx
      env: GENERATOR="Unix Makefiles"
      before_script:
        curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp
        DO_CMD=sudo bash
    - os: linux
      name: Install
      sudo: required
      before_script: test -e /usr/bin/cmake || sudo ln -s $(which cmake) /usr/bin/cmake
      script:
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp DO_CMD=sudo bash
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=EBI-Metagenomics GITHUB_PROJECT=imm DO_CMD=sudo bash
    - os: osx
      name: Install
      script:
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp DO_CMD=sudo bash
        - curl -fsSL https://git.io/JerYI | GITHUB_USER=EBI-Metagenomics GITHUB_PROJECT=imm DO_CMD=sudo bash
addons:
  apt:
    packages:
      - cmake
script:
  - mkdir prefix
  - mkdir build.release
  - cd build.release
  - cmake -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/prefix
    ..
  - cmake --build . --config Release
  - ctest --output-on-failure -C Release
  - cmake --build . --config Release --target install
  - test -e $TRAVIS_BUILD_DIR/prefix/include/imm/imm.h
  - test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/imm/imm-config.cmake
  - test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/imm/imm-targets-release.cmake
  - test -e $TRAVIS_BUILD_DIR/prefix/lib/cmake/imm/imm-targets.cmake
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then otool -l $TRAVIS_BUILD_DIR/prefix/lib/libimm.dylib | grep -q LC_RPATH; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then test -e $TRAVIS_BUILD_DIR/prefix/lib/libimm.so; fi
  - cd $TRAVIS_BUILD_DIR
  - git clean -xdfq
  - mkdir build.debug
  - cd build.debug
  - cmake -G"$GENERATOR" -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON ..
  - cmake --build . --config Debug
  - ctest --output-on-failure -C Debug
  - cd $TRAVIS_BUILD_DIR
  - git clean -xdfq
notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  on:
    tags: true
    repo: EBI-Metagenomics/imm
    branch: master
    skip_existing: true
