#!/bin/bash

bash -c "$(curl -fsSL https://git.io/Jz7Oa)" -s horta/hope || exit 1
bash -c "$(curl -fsSL https://git.io/Jz7Oa)" -s horta/logaddexp || exit 1
bash -c "$(curl -fsSL https://git.io/Jz7Oa)" -s horta/elapsed || exit 1
bash -c "$(curl -fsSL https://git.io/Jz7Oa)" -s EBI-Metagenomics/c-containers || exit 1
bash -c "$(curl -fsSL https://git.io/Jz7Oa)" -s EBI-Metagenomics/lite-pack || exit 1
