name: CMake

on: [push]

strategy:
  matrix:
    double_precision: ['On', 'Off']

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install logaddexp
      run: sudo /bin/bash -c "$(curl -fsSL https://git.io/JerYI)" -s horta/logaddexp

    - name: Install elapsed
      run: sudo /bin/bash -c "$(curl -fsSL https://git.io/JerYI)" -s horta/elapsed

    - name: Install cass
      run: sudo /bin/bash -c "$(curl -fsSL https://git.io/JerYI)" -s horta/cass

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DIMM_DOUBLE_PRECISION=${{matrix.double_precision}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

    - name: Install
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: sudo cmake --build . --target install --config $BUILD_TYPE
