name: Test

on: push

env:
  PREFIX: ${{github.workspace}}/deps
  C_INCLUDE_PATH: ${{github.workspace}}/deps/include
  LIBRARY_PATH: ${{github.workspace}}/deps/lib

jobs:
  test:
    name: Test on ${{ matrix.os }} with build type ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: ${{ matrix.build_type }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
        build_type: [Release, Debug]

    steps:
      - uses: actions/checkout@v4

      - name: clone lite-pack
        run: git clone --depth 1 https://github.com/EBI-Metagenomics/lip.git ${{github.workspace}}/lip

      - name: build & install lite-pack
        working-directory: ${{github.workspace}}/lip
        run: make && make install

      - name: build & install lite-pack-io
        working-directory: ${{github.workspace}}/lip/ext
        run: make && make install

      - name: make
        run: make

      - name: make check
        run: make check
