name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  test:
    name: Test on ${{ matrix.os }} with double precision ${{ matrix.double_precision }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        double_precision: ['On', 'Off']

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo ./install-deps

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCI_BUILD=ON -DIMM_DOUBLE_PRECISION=${{matrix.double_precision}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE --rerun-failed --output-on-failure

    - name: Install
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: sudo cmake --build . --target install --config $BUILD_TYPE
