name: Test

on: push

jobs:
  test:
    name: Test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    env:
      PREFIX:         ${{github.workspace}}/deps
      C_INCLUDE_PATH: ${{github.workspace}}/deps/include
      LIBRARY_PATH:   ${{github.workspace}}/deps/lib
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]

    steps:
      - uses: actions/checkout@v4

      - name: clone lite-pack
        run: git clone --depth 1 https://github.com/EBI-Metagenomics/lite-pack.git ${{github.workspace}}/lite-pack

      - name: build & install lite-pack
        working-directory: ${{github.workspace}}/lite-pack
        run: make && make install

      - name: build & install lite-pack-io
        working-directory: ${{github.workspace}}/lite-pack/ext
        run: make && make install

      - name: make
        run: make

      - name: make check
        run: make check
