name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        double_precision: ['On', 'Off']

    steps:
    - uses: actions/checkout@v2

    - name: Install containers
      run: sudo /bin/bash -c "$(curl -fsSL https://git.io/JerYI)" -s EBI-Metagenomics/c-containers

    - name: Install logaddexp
      run: sudo /bin/bash -c "$(curl -fsSL https://git.io/JerYI)" -s horta/logaddexp

    - name: Install elapsed
      run: sudo /bin/bash -c "$(curl -fsSL https://git.io/JerYI)" -s horta/elapsed

    - name: Install hope
      run: sudo /bin/bash -c "$(curl -fsSL https://git.io/JerYI)" -s horta/hope

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCI_BUILD=ON -DIMM_DOUBLE_PRECISION=${{matrix.double_precision}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

    - name: Install
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: sudo cmake --build . --target install --config $BUILD_TYPE
